import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "../styles/style.module.scss";
import Header from "@/componets/Header";
import Timeline from "@/componets/Timeline";
import Post from "@/componets/Post";
import Footer from "@/componets/Footer";


const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className={styles.container}>
        <Timeline />
      </main>
      <Footer />
    </>
  );
}